# permissions for end users to edit delta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delta-editor-role
rules:
- apiGroups:
  - routing.andrewneudegg.com
  resources:
  - delta
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - routing.andrewneudegg.com
  resources:
  - delta/status
  verbs:
  - get
